const Map<String, List<String>> websiteData = {
  'webpages': [
    'https://start.duckduckgo.com/',
    'https://www.google.com/',
    'https://www.bing.com/',
    'https://www.yahoo.com/',
    'https://yandex.com/',
    'https://startpage.com/',
    'https://www.ask.com/',
    'https://www.ecosia.org/',
    'https://www.wolframalpha.com/',
    'https://search.aol.com/',
  ],
  'webpages1': [
    "https://duckduckgo.com/?q",
    "https://www.google.com/search?q",
    "https://www.bing.com/search?q",
    "https://search.yahoo.com/search?q",
    "https://yandex.com/search/touch/?text",
    "https://startpage.com/search?q",
    "https://www.ask.com/web?q",
    "https://www.ecosia.com/search?method=index&q",
    "https://www.wolframalpha.com/input?i",
    "https://search.aol.com/aol/search?q",
  ],
  'images': [
    'assets/images/duck.png',
    'assets/images/google.png',
    'assets/images/bing.png',
    'assets/images/yahoo.png',
    'assets/images/yandex.png',
    'assets/images/start.png',
    'assets/images/ask.png',
    'assets/images/ecosia.png',
    'assets/images/wolfarm.png',
    'assets/images/aol.png',
  ]
};
